"""Stable fail-closed reason codes for the strategy snapshot collector."""

from __future__ import annotations

from enum import StrEnum
from typing import Final


class CollectorReason(StrEnum):
    """Machine-readable rejection reasons.

    The data-health and exclusion codes mirror the frozen accepted event
    policy exactly; collector-boundary codes are additive and never reinterpret
    strategy policy.
    """

    PRIMARY_RELEASE_MISSING = "PRIMARY_RELEASE_MISSING"
    PRIMARY_RELEASE_LATE = "PRIMARY_RELEASE_LATE"
    PUBLICATION_TIME_UNKNOWN = "PUBLICATION_TIME_UNKNOWN"
    RETRIEVED_AFTER_CUTOFF = "RETRIEVED_AFTER_CUTOFF"
    CONTENT_HASH_MISMATCH = "CONTENT_HASH_MISMATCH"
    UNPERMITTED_SOURCE_CLASS = "UNPERMITTED_SOURCE_CLASS"
    SOURCE_RIGHTS_UNVERIFIED = "SOURCE_RIGHTS_UNVERIFIED"
    MATERIAL_SOURCE_CONFLICT = "MATERIAL_SOURCE_CONFLICT"
    FEATURE_DEPENDENCY_LATE = "FEATURE_DEPENDENCY_LATE"
    FEATURE_DEPENDENCY_MISSING = "FEATURE_DEPENDENCY_MISSING"
    MARKET_OBSERVATION_MISSING = "MARKET_OBSERVATION_MISSING"
    MARKET_OBSERVATION_STALE = "MARKET_OBSERVATION_STALE"
    MARKET_OBSERVATION_ASYNCHRONOUS = "MARKET_OBSERVATION_ASYNCHRONOUS"
    BETA_INSUFFICIENT_OBSERVATIONS = "BETA_INSUFFICIENT_OBSERVATIONS"
    BETA_OUT_OF_BOUNDS = "BETA_OUT_OF_BOUNDS"
    BETA_ILL_CONDITIONED = "BETA_ILL_CONDITIONED"
    NON_FINITE_FEATURE = "NON_FINITE_FEATURE"
    CORPORATE_ACTION_UNRESOLVED = "CORPORATE_ACTION_UNRESOLVED"
    CLOCK_MISMATCH = "CLOCK_MISMATCH"
    POLICY_HASH_MISMATCH = "POLICY_HASH_MISMATCH"
    UNSUPPORTED_SECURITY_TYPE = "UNSUPPORTED_SECURITY_TYPE"
    UNSUPPORTED_PRIMARY_EXCHANGE = "UNSUPPORTED_PRIMARY_EXCHANGE"
    INACTIVE_SECURITY = "INACTIVE_SECURITY"
    PRICE_BELOW_MINIMUM = "PRICE_BELOW_MINIMUM"
    INSUFFICIENT_DOLLAR_VOLUME = "INSUFFICIENT_DOLLAR_VOLUME"
    INSUFFICIENT_LIQUIDITY_HISTORY = "INSUFFICIENT_LIQUIDITY_HISTORY"
    NOT_OPTIONABLE_AT_FREEZE = "NOT_OPTIONABLE_AT_FREEZE"
    EVENT_NOT_CONFIRMED = "EVENT_NOT_CONFIRMED"
    TIMING_BUCKET_UNKNOWN = "TIMING_BUCKET_UNKNOWN"
    TIMING_BUCKET_CONFLICT = "TIMING_BUCKET_CONFLICT"
    INTRADAY_EVENT = "INTRADAY_EVENT"
    SCHEDULE_CHANGED_AFTER_FREEZE = "SCHEDULE_CHANGED_AFTER_FREEZE"
    DUPLICATE_ISSUER_SESSION = "DUPLICATE_ISSUER_SESSION"
    LIVE_BOUNDARY_NOT_PINNED = "LIVE_BOUNDARY_NOT_PINNED"
    HOST_CONFIGURATION_MISSING = "HOST_CONFIGURATION_MISSING"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"
    DUPLICATE_OBSERVATION = "DUPLICATE_OBSERVATION"
    ADJUSTMENT_POLICY_VIOLATION = "ADJUSTMENT_POLICY_VIOLATION"
    PAGINATION_INCOMPLETE = "PAGINATION_INCOMPLETE"
    DUPLICATE_SOURCE_RECORD = "DUPLICATE_SOURCE_RECORD"
    RETRIEVAL_INCOMPLETE = "RETRIEVAL_INCOMPLETE"
    SCHEDULE_NOT_FROZEN = "SCHEDULE_NOT_FROZEN"
    RELEASE_OFF_SCHEDULE = "RELEASE_OFF_SCHEDULE"
    OFFICIAL_RELEASE_MISSING = "OFFICIAL_RELEASE_MISSING"
    OFFICIAL_RELEASE_LATE = "OFFICIAL_RELEASE_LATE"
    REQUIRED_COMPONENT_MISSING = "REQUIRED_COMPONENT_MISSING"
    REVISION_FIELD_MISSING = "REVISION_FIELD_MISSING"
    REVISION_FIELD_CONFLICTING = "REVISION_FIELD_CONFLICTING"
    MARKET_WINDOW_MISSING = "MARKET_WINDOW_MISSING"
    INSUFFICIENT_NORMALIZATION_HISTORY = "INSUFFICIENT_NORMALIZATION_HISTORY"
    NON_FULL_REGULAR_SESSION = "NON_FULL_REGULAR_SESSION"
    SOURCE_MATRIX_MISSING = "SOURCE_MATRIX_MISSING"
    SOURCE_MATRIX_DRIFT = "SOURCE_MATRIX_DRIFT"
    SOURCE_RIGHTS_BLOCKED = "SOURCE_RIGHTS_BLOCKED"
    SOURCE_RIGHTS_LIMITATION_UNMET = "SOURCE_RIGHTS_LIMITATION_UNMET"
    UNSAFE_OUTPUT_PATH = "UNSAFE_OUTPUT_PATH"


class CollectorRejected(ValueError):
    """A deterministic fail-closed collector error."""

    def __init__(self, reason: CollectorReason, path: str, detail: str) -> None:
        self.reason = reason
        self.path = path
        self.detail = detail
        super().__init__(f"{reason.value} at {path}: {detail}")


DATA_HEALTH_FAILURE_CODES: Final = frozenset(
    {
        CollectorReason.PRIMARY_RELEASE_MISSING,
        CollectorReason.PRIMARY_RELEASE_LATE,
        CollectorReason.PUBLICATION_TIME_UNKNOWN,
        CollectorReason.RETRIEVED_AFTER_CUTOFF,
        CollectorReason.CONTENT_HASH_MISMATCH,
        CollectorReason.UNPERMITTED_SOURCE_CLASS,
        CollectorReason.SOURCE_RIGHTS_UNVERIFIED,
        CollectorReason.MATERIAL_SOURCE_CONFLICT,
        CollectorReason.FEATURE_DEPENDENCY_LATE,
        CollectorReason.FEATURE_DEPENDENCY_MISSING,
        CollectorReason.MARKET_OBSERVATION_MISSING,
        CollectorReason.MARKET_OBSERVATION_STALE,
        CollectorReason.MARKET_OBSERVATION_ASYNCHRONOUS,
        CollectorReason.BETA_INSUFFICIENT_OBSERVATIONS,
        CollectorReason.BETA_OUT_OF_BOUNDS,
        CollectorReason.BETA_ILL_CONDITIONED,
        CollectorReason.NON_FINITE_FEATURE,
        CollectorReason.CORPORATE_ACTION_UNRESOLVED,
        CollectorReason.CLOCK_MISMATCH,
        CollectorReason.POLICY_HASH_MISMATCH,
    }
)
