"""Gate D expression comparison and deterministic compilation.

This package compares cash/no-trade, shares, one long option, and a
defined-risk debit vertical for the same frozen directional decisions, and
compiles only the promoted expression. It never places orders, touches
accounts or positions, or promotes policy.
"""

from ringdown_market.execution.expression.compiler import (
    COMPILED,
    COMPILED_EXPRESSION_SCHEMA,
    COMPILED_EXPRESSION_SCHEMA_VERSION,
    PINNED_FEEDS,
    CompiledExpression,
    compile_expression,
    compile_or_no_package,
    compiled_expression_bytes,
    compiled_expression_payload,
    compiled_expression_sha256,
    no_package_payload,
)
from ringdown_market.execution.expression.economics import (
    CONTRACT_MULTIPLIER,
    ExpressionEconomics,
    after_cost_edge_basis_points,
    cash_economics,
    debit_vertical_economics,
    option_economics,
    shares_economics,
)
from ringdown_market.execution.expression.observations import (
    EXECUTABLE_DATA,
    INDICATIVE_DATA,
    BorrowLocateEvidence,
    ExpressionMarketSnapshot,
    FeedIdentity,
    OptionContractObservation,
    PackageObservation,
    ShareObservation,
    TwoSidedQuote,
    expression_market_snapshot_bytes,
    expression_market_snapshot_payload,
    expression_market_snapshot_sha256,
)
from ringdown_market.execution.expression.policy import (
    AFTER_COST_OBJECTIVE,
    PROMOTED_EXPRESSION_POLICY_SCHEMA,
    PROMOTED_EXPRESSION_POLICY_SCHEMA_VERSION,
    PromotedExpressionPolicy,
    parse_promoted_expression_policy,
    promoted_expression_policy_bytes,
    promoted_expression_policy_payload,
    promoted_expression_policy_sha256,
)
from ringdown_market.execution.expression.reasons import (
    NO_EXPRESSION,
    NO_PACKAGE,
    ExpressionKind,
    ExpressionReason,
    ExpressionRejected,
)
from ringdown_market.execution.expression.tournament import (
    GATE_D_REPORT_SCHEMA,
    GATE_D_REPORT_SCHEMA_VERSION,
    GateDReport,
    TournamentEvent,
    gate_d_report_bytes,
    gate_d_report_payload,
    gate_d_report_sha256,
    run_gate_d_tournament,
)

__all__ = [
    "AFTER_COST_OBJECTIVE",
    "COMPILED",
    "COMPILED_EXPRESSION_SCHEMA",
    "COMPILED_EXPRESSION_SCHEMA_VERSION",
    "CONTRACT_MULTIPLIER",
    "EXECUTABLE_DATA",
    "GATE_D_REPORT_SCHEMA",
    "GATE_D_REPORT_SCHEMA_VERSION",
    "INDICATIVE_DATA",
    "NO_EXPRESSION",
    "NO_PACKAGE",
    "PINNED_FEEDS",
    "PROMOTED_EXPRESSION_POLICY_SCHEMA",
    "PROMOTED_EXPRESSION_POLICY_SCHEMA_VERSION",
    "BorrowLocateEvidence",
    "CompiledExpression",
    "ExpressionEconomics",
    "ExpressionKind",
    "ExpressionMarketSnapshot",
    "ExpressionReason",
    "ExpressionRejected",
    "FeedIdentity",
    "GateDReport",
    "OptionContractObservation",
    "PackageObservation",
    "PromotedExpressionPolicy",
    "ShareObservation",
    "TournamentEvent",
    "TwoSidedQuote",
    "after_cost_edge_basis_points",
    "cash_economics",
    "compile_expression",
    "compile_or_no_package",
    "compiled_expression_bytes",
    "compiled_expression_payload",
    "compiled_expression_sha256",
    "debit_vertical_economics",
    "expression_market_snapshot_bytes",
    "expression_market_snapshot_payload",
    "expression_market_snapshot_sha256",
    "gate_d_report_bytes",
    "gate_d_report_payload",
    "gate_d_report_sha256",
    "no_package_payload",
    "option_economics",
    "parse_promoted_expression_policy",
    "promoted_expression_policy_bytes",
    "promoted_expression_policy_payload",
    "promoted_expression_policy_sha256",
    "run_gate_d_tournament",
    "shares_economics",
]
